# Generated by Django 3.1.2 on 2020-10-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_auto_20201031_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='InValidUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Username')),
                ('message', models.CharField(max_length=100, verbose_name='Messge')),
            ],
            options={
                'verbose_name': 'InValid user',
            },
        ),
    ]
